"""empty message

Revision ID: 5201c54bdde2
Revises: 
Create Date: 2025-03-13 19:31:48.755888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5201c54bdde2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pk_sig', sa.String(length=130), nullable=False))
        batch_op.add_column(sa.Column('sk_enc', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('pk_enc', sa.String(length=130), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('pk_enc')
        batch_op.drop_column('sk_enc')
        batch_op.drop_column('pk_sig')

    # ### end Alembic commands ###
